# ===================================================================
# Gencraft Studio - Canonical Pre-Commit Configuration v1.0
# SSoT: gcs-devops-standards/.pre-commit-config.yaml
# ===================================================================

repos:
  # ===== Generic File Checks =====
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # ===== Commit Message Validation =====
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.22.0
    hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ["@commitlint/config-conventional"]

  # ===== Markdown Linting =====
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args: ["--config", ".markdownlint.yaml"]

  # ===== Gencraft SSoT Linters (Custom Hooks) =====
  - repo: https://github.com/GenCr-ft/gcd-ops-scripts.git
    rev: v2.6.0
    hooks:
      - id: metadata-linter
        name: SSoT Metadata Linter
        exclude: ^(tests/fixtures/|integration_test_docs/|README\.md)
      - id: naming-linter
        name: SSoT Naming Linter
        exclude: ^(tests/fixtures/|integration_test_docs/|README\.md)
      - id: link-linter
        name: SSoT Link Linter
        exclude: ^(tests/fixtures/|integration_test_docs/|README\.md)
